name: trough
dependencies:
   - python=3.7
   - matplotlib
   - numpy
   - xarray
   - pandas
   - cartopy
   - pip
   - pytest
   - astropy
   - scikit-learn
   - pip:
      - pymap3d
      - igrf12
      - h5py
      - unlzw2
      - tensorflow
# Manual install
# apexpy - https://github.com/space-physics/apexpy
