channels:
  - anaconda
  - conda-forge
dependencies:
   - numpy==1.26.*
   - scipy==1.7.*
   - h5py==3.6.*
   - scikit-image==0.19.*
   - scikit-learn==1.0.*
   - appdirs==1.4.*
   - bs4==4.10.*
   - pandas==1.3.*
   - xarray==0.20.*
   - bottleneck==1.3.*
   - cvxpy==1.1.*
   - pip
   - pip:
      - madrigalWeb==3.2
      - apexpy
