name: trough
channels:
  - conda-forge
dependencies:
   - numpy
   - scipy
   - pytest
   - h5py
   - scikit-image
   - scikit-learn
   - appdirs
   - bs4
   - pip
   - pip:
      - apexpy
      - madrigalWeb
