channels:
  - anaconda
  - conda-forge
dependencies:
   - numpy
   - scipy
   - h5py
   - scikit-image
   - appdirs
   - bs4
   - pandas
   - pytables
   - pip
   - pip:
      - apexpy
      - madrigalWeb
