channels:
  - conda-forge
dependencies:
   - scipy=1.7.0
   - h5py=3.3.0
   - scikit-image=0.18.2
   - appdirs=1.4.4
   - bs4=4.10.0
   - pandas=1.3.1
   - pytables=3.6.1
   - pip
   - pip:
      - madrigalWeb
