name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - run: |
        conda env create --file environment.yml --name test python=${{ matrix.python-version }}
        source activate test
        pip install apexpy
        pip install --upgrade numpy
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - run: |
        conda install pytest
        pip install pytest-html
        pip install -e .
        pytest test --html=${{ matrix.python-version }}-results.html --self-contained-html
    - run: mv test.log ${{ matrix.python-version }}-test.log
      if: always()
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ matrix.python-version }}-artifacts
        path: |
          ${{ matrix.python-version }}-results.html
          ${{ matrix.python-version }}-test.log